### PR TITLE
sort and remove duplicates on constants of dummy data

### PR DESCRIPTION
**Pull request by inoas**

### CODE REVIEW

**Comment by inoas** [comment]
What I did:

1. open the files with constants
2. copy constants to another file, split into lines based on `,`
3. sort ascending
4. remove duplicate lines
5. copy back into gleam file and save

**Comment by inoas** [comment]
There are no unit tests so I couldn't test but the gleam compiler did not complain in the vscode lsp when I saved the gleam files, at least.

**Comment by inoas** [comment]
The diffs make more sense comparing via `difftastic`.

**Comment by inoas** [comment]
... and I did this because when browsing I noticed `Europe/Berlin` was there twice as a time zone.

**Comment by massivefermion** [comment]
Thanks a lot. I tested a few functions and everything seems to be fine. I'll gradually add some tests though!
I should say that this is the first time anyone has sent a PR to any of my packages, so I really appreciate it! :)

**Pull request merged**
