### PR TITLE
French localization

### PR DESCRIPTION
**Pull request by PascalLeMerrer**
This PR adds the support for French (from France) language.
At the exception of the `finance.gleam` file, this new content is not a translation of the English files.
I collected lists of nouns, adjectives, conjunctions, first names, last names, etc, that are likely to appear in French.
So sometimes there is more content in the English version, while others there is more in the French one.

### CODE REVIEW

**Comment by massivefermion** [comment]
Thanks for the PR. I just have a few notes.

The language specific modules are supposed to be for concepts that may differ in that particular language. But timezone is not one of them. I don't think developers would need a random timezone in languages other than English. So please remove that. Basically if something is already in an English module, it shouldn't be in a localization unless it's going to actually localize it!

Now there may be a situation where developers in one country only use English for a particular concept but developers from another country do use their own language for that concept in which case I would like to have that concept in the language in which the developers actually use.

Another thing is about the `string` module. It seems like nothing in there is different from the English module. Maybe you can do something so that it's specifically more useful to French developers, otherwise I'd prefer not to have it.

This point may not make sense at all, but I'll include it anyway because it may be a useful example to demonstrate what I'm aiming for here. In the `address` module you have a function called `state`, which is the same name as the function in the English module. But if you look at the `fa/address` module, there is instead a `province` function, which is the usual term in my country. Now maybe the proper English translation for the equivalent French word is `state`, in which case no change is needed. But if administrative divisions in France are not usually called `state` when translated to English, I'd prefer the proper English translation be used instead of `state`. I hope I explained it well.

The same is true for `zip_code`(en) and `postal_code`(fa). But here I'd also appreciate at least an almost realistic pattern for the zip code equivalent in France. Of course the pattern you provided may already make sense, just wanted to make sure.

Thanks again, I really appreciate this PR. Hopefully we'll have many more localizations.

**Comment by PascalLeMerrer** [comment]
Thanks for your feedback @massivefermion 
I'll take it into account.

Suggestion: your comment above could be the base for a `Contributing.md` file

**Comment by PascalLeMerrer** [comment]
> I don't think developers would need a random timezone in languages other than English

May I ask why?
I really don't get the logic behind this.

I mean the timezone function just returns a string, not some abstraction for a timezone; and in French we usually use the French names for the region and city, not the English ones ("Afrique/Alger" and not "Africa/Algiers").

Could you explain this please?

**Comment by massivefermion** [comment]
That's just what I thought and apparently I was wrong. If you think having timezones in French would help developers, fair enough!

**Comment by PascalLeMerrer** [comment]
It took the rest of your feedbacks into account. Is it Ok now?

**Comment by massivefermion** [comment]
I think it's better to not have departments and department numbers as separate entities. You could have the `department` function return something like `#(String, String)`(or a Department type so that you can have named fields for more clarity) so that the association is clear. I assume it would be useful not having to handle the association yourself!

**Comment by massivefermion** [comment]
Also, the country codes and alpha3 country codes are the same as in English, so I think those can be removed too.

**Comment by PascalLeMerrer** [comment]
Hello
It's done.
I also fixed/improved the generated data for the addresses to be more realistic.
What is still not realistic and could be improved further is the fact that postal code are totally random. So they do not match the city when a full address is generated. This would mean I should introduce a city type with both a city name and a postal code. WDYT?

**Comment by massivefermion** [comment]
If the postal code for each city has a particular prefix or fits a particular pattern, you could put that pattern or prefix with its associated city, just like the departments.
Then, when generating a new postal code, you could get a random city and use the prefix/pattern to generate a postal code.
It may also be useful if you have a function that gets a city as an argument and only generates postal codes for that city.

**Comment by PascalLeMerrer** [comment]
In France only the largest cities have several postal codes.
The majority only have one.
I'll come up with something.

**Comment by PascalLeMerrer** [comment]
It's done.
`address.city()` returns a City, that has a name and a list of postal codes.  The codes are the real ones for the given city name.

**Comment by massivefermion** [comment]
Thanks
Just one little thing. Given that locales are internal modules, could you reexport `Department` and `City` types in `fr/address`?

**Comment by PascalLeMerrer** [comment]
How would you do that?

**Comment by massivefermion** [comment]
```gleam
import blah/locales/fr

pub type Department = fr.Department
pub type City = fr.City
```

**Comment by PascalLeMerrer** [comment]
Done.

**Comment by massivefermion** [comment]
I just realized the type of the `number` field in your `Department` type is `Int`, but some department numbers have a `0` prefix. Now maybe in this context `1` and `01` are not really different. But if it matters that the department number is `01` and not just `1`, then the `number` field should be of type `String`!

**Comment by PascalLeMerrer** [comment]
You're right. I changed it.

**Comment by massivefermion** [comment]
Thanks, this is a great addition to the package. Hopefully we'll have more localizations!
And if you're active on the discord, I'd appreciate it if you give me your username there so I can give you credit along with the announcement!

**Pull request merged**
